In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('GSE54651_WFat_quant.csv')
df

FileNotFoundError: [Errno 2] No such file or directory: 'GSE54651_WFat_quant.csv'

In [33]:
pip install mygene

Defaulting to user installation because normal site-packages is not writeable
Collecting mygene
  Downloading mygene-3.2.2-py2.py3-none-any.whl (5.4 kB)
Collecting biothings-client>=0.2.6
  Downloading biothings_client-0.2.6-py2.py3-none-any.whl (37 kB)
Requirement already satisfied: requests>=2.3.0 in /share/apps/anaconda-ci/fgci-centos7-anaconda/software/anaconda/2022-04/18a3eb7e/lib/python3.9/site-packages (from biothings-client>=0.2.6->mygene) (2.28.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /share/apps/anaconda-ci/fgci-centos7-anaconda/software/anaconda/2022-04/18a3eb7e/lib/python3.9/site-packages (from requests>=2.3.0->biothings-client>=0.2.6->mygene) (1.26.9)
Requirement already satisfied: idna<4,>=2.5 in /share/apps/anaconda-ci/fgci-centos7-anaconda/software/anaconda/2022-04/18a3eb7e/lib/python3.9/site-packages (from requests>=2.3.0->biothings-client>=0.2.6->mygene) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in /share/apps/anaconda-ci/fgci-centos7-anaconda/software/anaconda/2022-04/18a3eb7e/lib/python3.9/site-packages (from requests>=2.3.0->biothings-client>=0.2.6->mygene) (2022.12.7)
Requirement already satisfied: charset-normalizer<3,>=2 in /share/apps/anaconda-ci/fgci-centos7-anaconda/software/anaconda/2022-04/18a3eb7e/lib/python3.9/site-packages (from requests>=2.3.0->biothings-client>=0.2.6->mygene) (2.0.12)
Installing collected packages: biothings-client, mygene
Successfully installed biothings-client-0.2.6 mygene-3.2.2
Note: you may need to restart the kernel to use updated packages.

In [135]:
import mygene
mg = mygene.MyGeneInfo()
ens = df[df.columns[0]]
res = mg.querymany(ens, as_dataframe = True)

querying 1-1000...done.
querying 1001-2000...done.
querying 2001-3000...done.
querying 3001-4000...done.
querying 4001-5000...done.
querying 5001-6000...done.
querying 6001-7000...done.
querying 7001-8000...done.
querying 8001-9000...done.
querying 9001-10000...done.
querying 10001-11000...done.
querying 11001-12000...done.
querying 12001-13000...done.
querying 13001-14000...done.
querying 14001-15000...done.
querying 15001-16000...done.
querying 16001-17000...done.
querying 17001-18000...done.
querying 18001-19000...done.
querying 19001-20000...done.
querying 20001-21000...done.
querying 21001-22000...done.
querying 22001-23000...done.
querying 23001-24000...done.
querying 24001-25000...done.
querying 25001-26000...done.
querying 26001-27000...done.
querying 27001-28000...done.
querying 28001-29000...done.
querying 29001-30000...done.
querying 30001-31000...done.
querying 31001-32000...done.
querying 32001-33000...done.
querying 33001-34000...done.
querying 34001-35000...done.
querying 35001-36000...done.
querying 36001-37000...done.
querying 37001-37310...done.
Finished.
6319 input query terms found no hit:
	['ENSMUSG00000086802', 'ENSMUSG00000037513', 'ENSMUSG00000092215', 'ENSMUSG00000085062', 'ENSMUSG000
Pass "returnall=True" to return complete lists of duplicate or missing query terms.

In [136]:
pd.set_option('display.max_rows', 100)
df['Gene.ID'] = res[res.columns[4]].values

In [137]:
df

,Gene.ID,WFat_CT22,WFat_CT28,WFat_CT34,WFat_CT40,WFat_CT46,WFat_CT52,WFat_CT58,WFat_CT64
0,Hspa4l,935.964320,399.118123,329.646691,468.212002,593.450218,383.988587,375.329745,496.793307
1,Rsad1,139.285686,232.818905,304.237818,199.770454,155.582710,239.582623,291.550784,195.368155
2,Per3,669.813329,957.712933,3835.402473,2066.375635,538.483872,1191.349207,2937.625489,1558.160710
3,Sf1,2944.517137,3419.794177,3966.458764,3260.004099,3079.047051,3467.384124,3831.714561,3412.962047
4,Dbp,81.619637,550.066644,4921.297455,825.301689,121.112289,1179.862369,3190.973067,461.706782
...,...,...,...,...,...,...,...,...,...
37305,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37306,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37307,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37308,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37309,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [138]:
df2 = df.dropna(subset=['Gene.ID']).reset_index(drop=True)

In [139]:
df2.to_csv('WFat_annot.csv',index=False)

,Gene.ID,Adr_CT22,Adr_CT28,Adr_CT34,Adr_CT40,Adr_CT46,Adr_CT52,Adr_CT58,Adr_CT64
0,Sfpq,2143.447231,1360.187378,2228.913438,2690.219386,1930.621839,1642.175938,2300.145936,2393.456350
1,Hlf,493.908866,506.711385,967.855958,711.047652,487.056573,557.210670,1024.558428,694.762366
2,Ankrd13a,1714.024982,1514.162807,1597.576535,1809.161844,1664.878407,1440.892789,1652.539970,1884.542917
3,Dnaja4,468.993582,370.223469,494.595730,660.793156,461.907353,387.020039,513.505740,567.099781
4,St6galnac2,1310.250820,878.214428,849.864167,967.666353,1253.269496,862.408291,852.027041,1034.327472
...,...,...,...,...,...,...,...,...,...
30985,Mir3090,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
30986,Mir3101,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
30987,Mir125b-1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
30988,Snora26,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
30989,Mir3063,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [64]:
annot[idx]

0              Sfpq
1               Hlf
2          Ankrd13a
3            Dnaja4
4        St6galnac2
            ...
21804        Gm8741
21831       Gm18284
21836       Gm20507
21838        Gm2991
21847       Gm20427
Name: Gene.ID, Length: 13429, dtype: object

In [109]:
df = pd.read_csv('WFat_annot.csv')
annot = df.iloc[:,0]
df.drop(columns=df.columns[0], axis=1, inplace=True)

In [110]:
df2 = df.applymap(lambda x: 1 if float(x) > 20 else 0)
idx = df2[(df2 != 0).all(1)].index.to_numpy()  
clone = df.iloc[idx,:]
clone.insert(loc=0, column='Gene.ID', value=annot[idx])
clone

,Gene.ID,WFat_CT22,WFat_CT28,WFat_CT34,WFat_CT40,WFat_CT46,WFat_CT52,WFat_CT58,WFat_CT64
0,Hspa4l,935.964320,399.118123,329.646691,468.212002,593.450218,383.988587,375.329745,496.793307
1,Rsad1,139.285686,232.818905,304.237818,199.770454,155.582710,239.582623,291.550784,195.368155
2,Per3,669.813329,957.712933,3835.402473,2066.375635,538.483872,1191.349207,2937.625489,1558.160710
3,Sf1,2944.517137,3419.794177,3966.458764,3260.004099,3079.047051,3467.384124,3831.714561,3412.962047
4,Dbp,81.619637,550.066644,4921.297455,825.301689,121.112289,1179.862369,3190.973067,461.706782
...,...,...,...,...,...,...,...,...,...
21852,2610021A01Rik,267.038162,187.619631,177.862109,187.284801,165.830673,218.249924,230.559701,259.959259
21856,Gm17195,69.199258,88.692916,49.480436,53.688310,34.470421,77.125913,73.725486,88.513735
21858,Gm6665,694.654088,1008.029107,657.287418,1353.444827,817.973770,1032.174450,1137.383175,1245.571663
21864,Eif3s6-ps2,78.070958,100.632347,95.617600,101.133792,68.940842,91.894705,77.746876,70.970472
21893,Scnm1,325.591380,291.663244,316.942255,283.424332,290.669495,260.915322,292.221016,281.489627

In [111]:
clone.to_csv('High_exp_WFat.csv',index=False)